export const promoText = 'SPECIAL PROMO!!! GRATIS ONGKIR SELURUH DAERAH JABODETABEK !!!!';

export const storeInfo = {
  name: 'Apotek Mediva',
  tagline: 'Apotek Mediva',
  description: 'Kami menjual obat, obat injeksi dan keperluan medis lainnya',
  whatsapp: '6285280398887',
  phone: '0852-8039-8887',
  email: 'rukoinjeksi@gmail.com',
  address: 'Jln Pramuka Raya Matraman Jakarta Timur',
  bank: {
    name: 'BCA',
    logo: 'https://brdsg.com/logo/id/bca.svg',
    account: '3423377239',
    holder: 'IRIL EFENDI',
  },
  benefits: [
    'Harga bersahabat boleh di tawar',
    'Dijamin 100% Produk Original',
    'Pengiriman Jamin Aman dan Tidak Pecah',
    'Bisa di kirim seluruh Indonesia',
  ],
};

export const injeksiProducts = [
  { id: 'p1', name: 'LIXIANA 60 mg Edoxaban Tosylate 28 Tablet – Obat Antikoagulan Pengencer Darah', oldPrice: 1200000, price: 1100000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LSc8AWldEY1u0D4LScdvYHiLPRbTrBQhe7NTXyNVYCCg.jpg', description: 'Obat antikoagulan golongan penghambat faktor Xa yang bekerja mencegah pembekuan darah. Digunakan untuk pencegahan stroke pada pasien fibrilasi atrium non-valvular serta pengobatan trombosis vena dalam (DVT) dan emboli paru. Diminum sekali sehari sesuai anjuran dokter.' },
  { id: 'p2', name: 'AssuCryl PGA Absorbable Suture 2-0 USP Metric 3 90cm Violet HRG38 Benang Bedah Serap Steril', oldPrice: 1100000, price: 850000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LS7OARECLdQiLceLS7dRVANnCT9512QiGHlDVAjwJZGA.jpg', description: 'Benang bedah steril berbahan Polyglycolic Acid (PGA) yang dapat diserap tubuh dalam 60-90 hari. Cocok untuk penutupan jaringan lunak, ligasi pembuluh darah, serta operasi ginekologi dan bedah umum. Warna violet memudahkan identifikasi saat penjahitan.' },
  { id: 'p3', name: 'Alovell 10 mg Alendronate Sodium Tablet Original Novell 30 Tablet Obat Resep', oldPrice: 840000, price: 700000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LS7IVA1yn6mPi6iLS7kgXjaGMoGaxQrKox2YNRvVRQ.jpg', description: 'Obat golongan bifosfonat untuk pengobatan dan pencegahan osteoporosis pada wanita pascamenopause serta osteoporosis akibat penggunaan glukokortikoid. Membantu meningkatkan kepadatan tulang dan mengurangi risiko patah tulang. Dikonsumsi 30 menit sebelum makan pagi dengan air putih.' },
  { id: 'p4', name: 'Xenical Orlistat 120 mg Kapsul Original Cheplapharm 21 Kapsul Obat Resep Penurun Berat Badan', oldPrice: 350000, price: 320000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LS7OlQooyR4zL77LS7T4idet2Reug5TliTsqDjd0dPZw.jpg', description: 'Obat penurun berat badan yang bekerja dengan menghambat enzim lipase pada saluran cerna, sehingga lemak dari makanan tidak diserap tubuh. Diindikasikan untuk penderita obesitas dengan BMI di atas 30, atau di atas 27 dengan faktor risiko. Digunakan bersama diet rendah lemak dan olahraga teratur.' },
  { id: 'p5', name: 'Lipitor Atorvastatin Calcium 20 mg Tablet Original Pfizer Obat Penurun Kolesterol 1 Strip', oldPrice: 320000, price: 250000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LS7724PxuAWpL0iLS7Xojg90pAtIq0RIOggyKi4JMPmA.jpg', description: 'Obat golongan statin untuk menurunkan kadar kolesterol jahat (LDL) dan trigliserida serta meningkatkan kolesterol baik (HDL) dalam darah. Membantu mencegah penyakit kardiovaskular seperti serangan jantung dan stroke. Diminum sekali sehari, bisa pagi atau malam.' },
  { id: 'p6', name: 'Spiriva Respimat Tiotropium Bromide 2.5 mcg Cartridge Inhalation Solution Refill Pack Original Boehringer Ingelheim', oldPrice: 750000, price: 340000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LS7IKwQBKO7UxcLS7jq9rd9xiH9AhSLLVb7wZSjHxw.jpg', description: 'Inhaler bronkodilator kerja panjang (LAMA) untuk terapi pemeliharaan Penyakit Paru Obstruktif Kronik (PPOK) dan asma. Membantu melebarkan saluran napas selama 24 jam sehingga memperbaiki sesak napas. Digunakan sekali sehari dengan 2 semprotan pada waktu yang sama.' },
  { id: 'p7', name: 'Zenon 10 mg/10 mg Rosuvastatin Ezetimibe Tablet Salut Selaput 30 Tablet Original Sanofi Obat Kolesterol', oldPrice: 800000, price: 700000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LSKZmNi0fKITnsUWLSKaSH1W1MRGOloQ4eBVWweBb0ssw.jpg', description: 'Kombinasi Rosuvastatin dan Ezetimibe yang bekerja ganda: menghambat produksi kolesterol di hati dan mengurangi penyerapan kolesterol di usus. Diberikan pada pasien hiperkolesterolemia yang tidak terkontrol dengan statin tunggal. Diminum sekali sehari bersama atau tanpa makanan.' },
  { id: 'p8', name: 'Farmadol 100 Paracetamol Infusion 10 mg/mL 100 mL Original Fahrenheit – Cairan Infus Parasetamol', oldPrice: 120000, price: 80000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LBMxdJPLfmFtnzLBQ03VS2aKiZPGLSkq71RdWln9Z3g.jpg', description: 'Sediaan infus parasetamol untuk penanganan nyeri sedang dan penurun demam pada pasien yang tidak dapat menggunakan sediaan oral. Umum digunakan di rumah sakit untuk pasien pascaoperasi. Diberikan melalui infus intravena dalam 15 menit sesuai dosis dokter.' },
  { id: 'p9', name: 'Floragyn Oral Probiotic Kapsul 30 Kapsul Original LAPI – Probiotik Kesehatan Organ Intim Wanita', oldPrice: 700000, price: 580000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LBMxdJPLfmFtnzLBQ8J9Hofsdr1VRSaq0VQgpiXxHQQ.jpg', description: 'Suplemen probiotik oral berisi Lactobacillus untuk menjaga keseimbangan flora normal saluran cerna dan organ intim wanita. Membantu mencegah infeksi jamur (kandidiasis) dan bakterial vaginosis. Dikonsumsi 1 kapsul sehari setelah makan.' },
  { id: 'p10', name: 'SILTERO Sildenafil Citrate 20 mg Tablet Salut Selaput Original 9 Blister x 10 Tablet Obat Resep', oldPrice: 3500000, price: 1800000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LBrchzCzExNNhx3LBBOAKBfy6ClfuSriwBaSGURPujQ.jpg', description: 'Obat resep golongan penghambat PDE5 yang diindikasikan untuk pengobatan hipertensi arteri pulmonal (PAH). Bekerja melebarkan pembuluh darah paru sehingga memperbaiki kapasitas kerja jantung dan pernapasan. Penggunaan harus di bawah pengawasan dokter spesialis.' },
  { id: 'p11', name: 'Cialis 5 mg Tadalafil Tablet Salut Selaput Original Lilly 28 Tablet (2 Blister x 14) Obat Resep', oldPrice: 1800000, price: 1500000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LBraa4btURUIHmNLBB75YEKo9PoayRTEKHUBAM4ohBaw.jpg', description: 'Obat resep dengan kandungan Tadalafil untuk pengobatan disfungsi ereksi dan pembesaran prostat jinak (BPH). Bekerja meningkatkan aliran darah pada jaringan tertentu. Diminum sekali sehari sesuai anjuran dokter, tidak boleh dikombinasi dengan obat golongan nitrat.' },
  { id: 'p12', name: 'Budesma 0.25 Budesonide Suspension for Nebulisation 0.25 mg/ml 20 Monodose x 2 mL Original Dexa Medica', oldPrice: 550000, price: 430000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LBWLp4TSkhY0eaLBWkY0tafDbWOtTQCibr1aZihz6Q.jpg', description: 'Suspensi kortikosteroid inhalasi untuk terapi asma bronkial dan croup pada anak. Diberikan menggunakan alat nebulizer untuk mengurangi peradangan saluran napas. Kemasan monodose steril siap pakai memudahkan pemberian dosis yang tepat.' },
  { id: 'p13', name: 'Farbivent Nebulizer Solution Ipratropium Bromide + Salbutamol Sulphate 2.5 mL 10 Ampul Original', oldPrice: 180000, price: 130000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LBWChyfxSxVm7zLBWkKjo4Pu4hXcpRdWLAHJiDBhJfg.jpg', description: 'Kombinasi bronkodilator Ipratropium dan Salbutamol dalam bentuk cairan nebulisasi untuk melegakan sesak napas akibat asma dan PPOK. Bekerja cepat melebarkan saluran napas. Digunakan dengan alat nebulizer sesuai jadwal yang diresepkan dokter.' },
  { id: 'p14', name: 'Depakote ER Divalproex Sodium 500 mg Extended Release Tablet Original Abbott 100 Tablet', oldPrice: 1600000, price: 900000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LBTpZ9e4Mna0Q9LBRSeGhl6jbWGK0R06IFCljoZIw.jpg', description: 'Obat antiepilepsi lepas lambat untuk terapi kejang, gangguan bipolar (fase mania), dan pencegahan migrain. Bekerja menstabilkan aktivitas listrik otak. Sediaan extended release memberi kadar obat stabil selama 24 jam, diminum sekali sehari sesuai resep.' },
  { id: 'p15', name: 'Hepamed Tenofovir Disoproxil Fumarate 300 mg Kaplet Salut Selaput Original DIPA Healthcare', oldPrice: 450000, price: 350000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LBRHjzoZH4kvhoNLBRB6pF9nEeqlRTxOOFDmoGa1dng.jpg', description: 'Obat antivirus golongan nucleotide reverse transcriptase inhibitor untuk pengobatan hepatitis B kronik dan infeksi HIV-1. Membantu menekan replikasi virus dan memperbaiki fungsi hati. Diminum sekali sehari bersama makanan sesuai anjuran dokter.' },
  { id: 'p16', name: 'Sildenafil Citrate 100 mg Tablet Salut Selaput Generik Original Amarox Box 1 Blister @4 Tablet', oldPrice: 250000, price: 160000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LBRHjzoZH4kvhoNLBRBvj79tbS7G31RPGQoj8MfcLaKw.jpg', description: 'Obat resep generik dengan kandungan Sildenafil Citrate untuk pengobatan disfungsi ereksi pada pria dewasa. Bekerja dengan meningkatkan aliran darah pada organ tertentu ketika ada rangsangan. Digunakan sekitar 30-60 menit sebelum aktivitas dan hanya dengan resep dokter.' },
];

export const insulinProducts = [
  { id: 'i1', name: 'NovoRapid FlexPen 100 U/ml – Insulin Aspart 5x3ml | Pen Insulin Cepat untuk Diabetes Per Bok', oldPrice: 700000, price: 550000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/Coy2fLtFcyHah3ACopL3XKvtEeb0xdT92aTIEcgTySMg.jpg', description: 'Insulin analog kerja cepat (Insulin Aspart) dalam bentuk pen siap pakai. Diberikan sesaat sebelum atau setelah makan untuk mengontrol lonjakan gula darah pada pasien diabetes tipe 1 dan tipe 2. Onset 10-20 menit dengan durasi kerja 3-5 jam.' },
  { id: 'i2', name: 'RYZODEG FlexTouch 100U/mL – Insulin untuk Diabetes | Tersedia di Jakarta', oldPrice: 1200000, price: 850000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/CorFkA6bpAreL6QCoBAQqgWPuRQuQ5CdmuYNdFZr3w.jpg', description: 'Kombinasi Insulin Degludec (basal ultra-long acting) dan Insulin Aspart (bolus cepat) dalam satu pen FlexTouch. Memberi kontrol gula darah puasa dan setelah makan dengan satu-dua kali injeksi sehari. Praktis untuk pasien yang butuh terapi kombinasi.' },
  { id: 'i3', name: 'Ryzodeg FlexTouch 100 IU/ml – Insulin Degludec/Insulin Aspart Pen 3 ml | Novo Nordisk', oldPrice: 210000, price: 175000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/CoQICBKsVesLCVXCoVb1v8tsnaLI4PTTquxS1TH1jxQ.jpg', description: 'Pen insulin kombinasi 70% Insulin Degludec dan 30% Insulin Aspart untuk terapi diabetes tipe 1 dan tipe 2. Isi 3 mL siap pakai dengan tombol FlexTouch yang mudah ditekan. Diberikan sesuai jam makan utama yang ditentukan dokter.' },
  { id: 'i4', name: 'Glaritus DispoPen-2 Insulin Glargine 100 IU/mL – Obat Diabetes Suntik Subkutan 3mL – Original BPOM', oldPrice: 750000, price: 550000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/CYcDIsNtdielixACYG01vgznFszaHARU2tSfDvmSaCYQ.jpg', description: 'Insulin basal analog kerja panjang (Insulin Glargine) yang memberi kontrol gula darah stabil selama 24 jam. Digunakan sekali sehari pada waktu yang sama. Cocok sebagai insulin dasar untuk pasien diabetes tipe 1 maupun tipe 2 yang perlu terapi basal.' },
  { id: 'i5', name: 'Humalog Mix50 KwikPen Insulin Lispro 100 U/mL – Pen Suntik Insulin untuk Diabetes', oldPrice: 950000, price: 650000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/CbU037MDlpMgCTyCbUDzrntAiL1QETQtOivEqv1NNRw.jpg', description: 'Insulin campuran 50% Insulin Lispro dan 50% Insulin Lispro Protamine yang memberi efek kerja cepat sekaligus menengah. Ideal untuk pasien yang membutuhkan kontrol gula darah setelah makan dan basal ringan. Diinjeksi 15 menit sebelum atau segera sesudah makan.' },
  { id: 'i6', name: 'Apidra SoloStar Insulin Glulisine 100 IU/mL – Pen Suntik Insulin untuk Diabetes', oldPrice: 650000, price: 500000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/CbU8HVhDgekh6JCbUuRleUAOQ4iwSQRq89OQc8tNA.jpg', description: 'Insulin analog kerja sangat cepat (Insulin Glulisine) dalam pen SoloStar. Onset kerja 10-20 menit sehingga cocok diinjeksi tepat sebelum makan. Menutupi lonjakan glukosa postprandial pada pasien diabetes tipe 1 dan tipe 2.' },
  { id: 'i7', name: 'Sansulin Rapid Insulin Aspart 100 IU/mL – Pen Injeksi 3 mL Disposable untuk Terapi Diabetes', oldPrice: 140000, price: 110000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/CUB2yWiNW0whLT0CUB9j3ujepvBwN0REHwEvEJLEdQ.jpg', description: 'Insulin Aspart kerja cepat dalam pen disposable 3 mL. Bekerja dalam 10-20 menit dan efektif menutupi kenaikan gula darah setelah makan. Praktis dibawa, dapat digunakan sebelum atau segera setelah makan sesuai instruksi dokter.' },
  { id: 'i8', name: 'EZ Rapid Insulin Aspart Pen Diabetes Original EZ Rapid Pen Injeksi Insulin Aspart Kerja Cepat', oldPrice: 170000, price: 120000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LRF9GMemrcrKOrLRwlip9ge0AZtLUTAiHbRWpsILqeA.jpg', description: 'Pen insulin Aspart generik dengan kerja cepat untuk mengendalikan glukosa darah pascamakan pada pasien diabetes. Onset 10-20 menit, puncak 1-3 jam. Alternatif ekonomis untuk pasien yang butuh terapi insulin bolus jangka panjang.' },
  { id: 'i9', name: 'Lantus SoloStar Insulin Glargine Pen Injeksi Obat Diabetes Long Acting Insulin', oldPrice: 190000, price: 140000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LRw8O8ToXd2NhoWLRwgpx4HtzJUAm5RHSL0Lmt9IyYQ.jpg', description: 'Insulin basal Glargine kerja panjang dalam pen SoloStar. Memberi profil kadar insulin datar tanpa puncak yang tajam selama 24 jam. Diinjeksi sekali sehari di waktu yang konsisten untuk mengontrol gula darah puasa.' },
  { id: 'i10', name: 'Apidra SoloStar Insulin Glulisine Pen Injeksi Obat Diabetes Rapid Acting Insulin', oldPrice: 150000, price: 120000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LRw8CezCz0MyhVxLRwwkRePdDTtfLVQoGCBu0hYea7A.jpg', description: 'Pen Insulin Glulisine kerja sangat cepat produksi Sanofi. Cocok untuk mengendalikan gula darah tepat sebelum atau setelah makan. Bagian dari terapi basal-bolus bersama insulin basal jangka panjang.' },
  { id: 'i11', name: 'Lantus SoloStar 100 IU/mL Insulin Glargine Pen – Obat Diabetes Long Acting Original Lantus SoloStar by Sanofi', oldPrice: 850000, price: 600000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LRLryD4OpbELCdYLRi3wuIHdBwIZtRAKCA1roWz4LMA.jpg', description: 'Insulin Glargine 100 IU/mL produksi Sanofi dalam pen SoloStar original. Insulin basal generasi analog yang bekerja stabil hingga 24 jam. Menjadi standar terapi basal pada diabetes tipe 1 dan tipe 2 di banyak pedoman internasional.' },
  { id: 'i12', name: 'Sansulin Log-G Dispoppen Insulin Glargine 100 IU/mL Pen 3 mL Box 5 Disposable Pen Insulin Diabetes Long Acting Original SANBE', oldPrice: 1350000, price: 650000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/Lmp0DbqbnWHy0RKLmpsHX87tOHoCpqSGma59ae3wZF3A.jpg', description: 'Pen insulin Glargine biosimilar produksi SANBE dengan kemasan isi 5 pen disposable. Alternatif ekonomis untuk terapi insulin basal jangka panjang. Diinjeksi subkutan sekali sehari pada waktu yang sama.' },
  { id: 'i13', name: 'Wegovy FlexTouch Semaglutide Injection Pen 0.5 mg & 1.7 mg Original Novo Nordisk Obat Suntik Penurun Berat Badan Once Weekly', oldPrice: 4000000, price: 3700000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LmvFEeuqO4NCWmLmvFgPLbGt1EnoQCWMAzuhJKG2oQ.jpg', description: 'Obat suntik Semaglutide golongan GLP-1 receptor agonist untuk manajemen berat badan pada obesitas dan overweight dengan komorbid. Bekerja mengurangi nafsu makan dan memperlambat pengosongan lambung. Diberikan sekali seminggu dengan titrasi dosis bertahap.' },
  { id: 'i14', name: 'Wegovy FlexTouch 0.25 mg Semaglutide Injection Pen Original Novo Nordisk Obat Suntik Diet Obesitas Weekly Dose 1 Pen 4 Dosis', oldPrice: 4000000, price: 3600000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LmvwEegZQxHlfvLLmvPSiXEgGb7nyVSpeprKVJbUhz8w.jpg', description: 'Dosis awal Wegovy 0.25 mg untuk fase titrasi 4 minggu pertama sebelum ditingkatkan bertahap. Meminimalkan efek samping gastrointestinal saat memulai terapi. Berisi 4 dosis mingguan dalam satu pen FlexTouch.' },
  { id: 'i15', name: 'Wegovy 1.7 mg FlexTouch Pen Semaglutide Original Obat Suntik Penurun Berat Badan Once Weekly Novo Nordisk', oldPrice: 6500000, price: 5000000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/Lm4LncKKHVF9fSqLm4cXXeh9DLXa9GTWuUeicI0E2V6w.jpg', description: 'Wegovy dosis pemeliharaan 1.7 mg untuk terapi penurunan berat badan jangka panjang. Diberikan sekali seminggu pada hari yang sama. Efektif dikombinasikan dengan diet rendah kalori dan aktivitas fisik teratur.' },
  { id: 'i16', name: 'Soliqua Pen – Insulin Glargine + Lixisenatide 100 unit/5 mcg per ml | Obat Diabetes Original', oldPrice: 750000, price: 500000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LCXE2zgigjmnCkrLCmOEcOnF3bfwKfT8ipRrygtz9lw.jpg', description: 'Kombinasi tetap Insulin Glargine (basal) dan Lixisenatide (GLP-1) dalam satu pen. Mengontrol gula darah puasa dan pascamakan sekaligus untuk pasien diabetes tipe 2 yang belum terkontrol dengan obat oral. Diinjeksi sekali sehari sebelum makan.' },
];

export const asmaProducts = [
  { id: 'a1', name: 'Symbicort Turbuhaler 160/4.5 µg (120 Dosis) | Inhaler Asma & PPOK – AstraZeneca', oldPrice: 850000, price: 340000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/CorFT6fu6Iy7rJCoB8bj8ig4Lp6LySa2BTrlPYLF4Nw.jpg', description: 'Inhaler kombinasi Budesonide (kortikosteroid) dan Formoterol (bronkodilator kerja panjang) untuk terapi pemeliharaan dan pereda asma serta PPOK. Sistem Turbuhaler bebas propelan dengan 120 dosis. Digunakan 1-2 kali sehari sesuai anjuran dokter.' },
  { id: 'a2', name: 'Symbicort Rapihaler 160/4.5 mcg - Inhaler Asma & PPOK (120 Dosis) - AstraZeneca', oldPrice: 560000, price: 390000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/CqJzbPW0faYEOHf5CqYweH3Xd8fAOGdRUiJj4qMTaj7Q.jpg', description: 'Inhaler Symbicort format MDI (metered-dose inhaler) berisi Budesonide dan Formoterol. Cocok untuk pasien yang lebih nyaman menggunakan aerosol dibanding dry powder. Efektif mengontrol gejala asma persisten dan PPOK dengan 120 dosis per canister.' },
  { id: 'a3', name: 'Symbicort Turbuhaler 160/4.5 mcg 60 Dosis - Inhaler Asma & PPOK | AstraZeneca', oldPrice: 350000, price: 285000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/CoevMefNgTEFCCyCoexPOd4Ss9EfMMTgy6wnuOOLZIlg.jpg', description: 'Kemasan 60 dosis Symbicort Turbuhaler yang cocok untuk pemakaian pemeliharaan 1 bulan. Mengandung kombinasi Budesonide dan Formoterol untuk mengurangi peradangan dan melebarkan saluran napas. Praktis dibawa dan mudah digunakan.' },
  { id: 'a4', name: 'Lantus SoloStar 100 IU/mL Insulin Glargine Pen – Obat Diabetes Long Acting Original Lantus SoloStar by Sanofi', oldPrice: 850000, price: 600000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LRLryD4OpbELCdYLRi3wuIHdBwIZtRAKCA1roWz4LMA.jpg', description: 'Insulin basal Glargine kerja panjang 24 jam produksi Sanofi. Pilihan utama untuk mengontrol gula darah puasa pada pasien diabetes tipe 1 dan tipe 2. Digunakan sekali sehari di waktu yang konsisten.' },
  { id: 'a5', name: 'Seretide Diskus 50/250 mcg Inhaler Salmeterol Fluticasone Obat Asma & COPD 60 Dosis Original GSK', oldPrice: 290000, price: 230000, image: 'https://brdsg.com/img/600/brzvhxzvbr1vbtsto9_1/LkBeHkYyLBpTHkbLkSKSOkNYeNeh9LTNGr2r439t0rdg.jpg', description: 'Inhaler dry powder Diskus kombinasi Salmeterol (bronkodilator kerja panjang) dan Fluticasone (kortikosteroid). Digunakan dua kali sehari untuk terapi pemeliharaan asma dan PPOK. Membantu mengurangi frekuensi serangan sesak napas.' },
];

export const provinces = ['Aceh','Bali','Bangka Belitung','Banten','Bengkulu','DKI Jakarta','Gorontalo','Jambi','Jawa Barat','Jawa Tengah','Jawa Timur','Kalimantan Barat','Kalimantan Selatan','Kalimantan Tengah','Kalimantan Timur','Kalimantan Utara','Kepulauan Riau','Lampung','Maluku','Maluku Utara','Nusa Tenggara Barat','Nusa Tenggara Timur','Papua','Papua Barat','Riau','Sulawesi Barat','Sulawesi Selatan','Sulawesi Tengah','Sulawesi Tenggara','Sulawesi Utara','Sumatera Barat','Sumatera Selatan','Sumatera Utara','Yogyakarta'];

export const cities = ['Jakarta Barat','Jakarta Pusat','Jakarta Selatan','Jakarta Timur','Jakarta Utara','Kab. Kepulauan Seribu'];

export const districts = ['Cempaka Putih','Gambir','Jakarta Pusat','Johar Baru','Kemayoran','Menteng','Sawah Besar','Senen','Tanah Abang'];

export const shippingRates = [
  { courier: 'JNE', service: 'REG', price: 10000, estimate: '1-2 hari', logo: 'https://brdsg.com/logo/id/jne.svg' },
  { courier: 'J&T', service: 'Reguler', price: 10000, estimate: '? hari', logo: null },
  { courier: 'TIKI', service: 'Reguler', price: 9000, estimate: '2 day hari', logo: null },
  { courier: 'NINJA', service: 'Standard', price: 8800, estimate: '? hari', logo: null },
];
